name: CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: mbologna/.github/.github/workflows/node-ci.yml@79e90cadfb3336caf16e4f749548dbea92d8d3bc # main
    with:
      node_version: lts/*
      package_manager: npm
      test_command: ""
