name: CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: mbologna/.github/.github/workflows/node-ci.yml@efd33bde6e56c880365e83aab71f3242f40bc7f3 # main
    with:
      node_version: lts/*
      package_manager: npm
      test_command: ""

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v4
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npm audit --audit-level=moderate
