name: CI

"on":
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: write

jobs:
  ci:
    uses: mbologna/.github/.github/workflows/node-ci.yml@b9144ddda9cdf36ebba426f1314b544d5245e7ac # main
    with:
      node_version: lts/*
      package_manager: npm
      test_command: "npm run check"
      enable_audit: true
      enable_release_drafter: true

  auto-release:
    if: github.event_name == 'schedule'
    uses: mbologna/.github/.github/workflows/auto-release.yml@b9144ddda9cdf36ebba426f1314b544d5245e7ac # main
    with:
      strategy: commits
    secrets: inherit
