name: Publish to npm

"on":
  release:
    types: [published]

jobs:
  publish:
    uses: mbologna/.github/.github/workflows/npm-publish.yml@ac8d6f1d386411c72e4bf328ba8e0df53f751ed6 # main
    with:
      node_version: lts/*
      package_manager: npm
    secrets: inherit

