name: Publish to npm

"on":
  release:
    types: [published]

jobs:
  publish:
    uses: mbologna/.github/.github/workflows/npm-publish.yml@60c0ffe12ebfe88e773c2780a7f71d80829ddfb4 # main
    with:
      node_version: lts/*
      package_manager: npm
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
