name: Publish to npm

"on":
  release:
    types: [published]

jobs:
  publish:
    uses: mbologna/.github/.github/workflows/npm-publish.yml@bc67bfd693eafaf8371ae6ba2626e1f977ab3311 # main
    with:
      node_version: lts/*
      package_manager: npm
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
